In [2]:
import os

file = open('train.csv','r')
txt = file.read()
txt[:100]

'Id,DetectedCamera,AngleOfSign,SignAspectRatio,SignWidth,SignHeight,SignFacing (Target)\n2c9180975a056'

In [3]:
data = dict()
Rows = txt.split('\n')
for eachRow in Rows[1:20]:
    print(eachRow)
    tokens = eachRow.split(',')
    print(tokens)

2c9180975a056a64015a1e0a52e57021,Rear,195,1.02,46,45,Rear
['2c9180975a056a64015a1e0a52e57021', 'Rear', '195', '1.02', '46', '45', 'Rear']
2c9180975a056a64015a1e17b32171e4,Rear,203,1.09,59,54,Rear
['2c9180975a056a64015a1e17b32171e4', 'Rear', '203', '1.09', '59', '54', 'Rear']
2c9180975a056a64015a1de4deb16bd5,Front,26,0.96,104,108,Front
['2c9180975a056a64015a1de4deb16bd5', 'Front', '26', '0.96', '104', '108', 'Front']
2c9180975a056a64015a1de4deb16bdd,Rear,199,0.81,38,47,Rear
['2c9180975a056a64015a1de4deb16bdd', 'Rear', '199', '0.81', '38', '47', 'Rear']
2c9180975a056a64015a1de4deb16bd6,Rear,208,0.93,54,58,Rear
['2c9180975a056a64015a1de4deb16bd6', 'Rear', '208', '0.93', '54', '58', 'Rear']
2c9180975a056a64015a1e44ba4377f6,Front,29,0.83,65,78,Front
['2c9180975a056a64015a1e44ba4377f6', 'Front', '29', '0.83', '65', '78', 'Front']
2c9180975a056a64015a1e01fd466f56,Left,245,0.93,109,117,Rear
['2c9180975a056a64015a1e01fd466f56', 'Left', '245', '0.93', '109', '117', 'Rear']
2c9180975a056a64015a1e

In [4]:
import pandas as pd
mainList = []
corres_Dict = {'Front':1,'Left':2,'Right':3,'Rear':4}
Rows = txt.split('\n')
end = len(Rows)
for eachRow in Rows[1:end-1]:
#    print(eachRow)
    tokens = eachRow.split(',')
#    print(tokens)
    data = dict()
    data['ID'] = tokens[0]
    data['DetectedCamera'] = corres_Dict[tokens[1]]
    data['AngleOfSign'] = tokens[2]
    data['SignAspectRatio'] = tokens[3]
    data['SignWidth'] = tokens[4]
    data['SignHeight'] = tokens[5]
    data['SignFacing'] = corres_Dict[tokens[6]]
    mainList.append(data)

dataset = pd.DataFrame(mainList)
dataset.head()

AngleOfSign  DetectedCamera                                ID  \
0         195               4  2c9180975a056a64015a1e0a52e57021   
1         203               4  2c9180975a056a64015a1e17b32171e4   
2          26               1  2c9180975a056a64015a1de4deb16bd5   
3         199               4  2c9180975a056a64015a1de4deb16bdd   
4         208               4  2c9180975a056a64015a1de4deb16bd6   

  SignAspectRatio  SignFacing SignHeight SignWidth  
0            1.02           4         45        46  
1            1.09           4         54        59  
2            0.96           1        108       104  
3            0.81           4         47        38  
4            0.93           4         58        54

In [5]:
dataset.shape

(38485, 7)

In [6]:
list(dataset["SignWidth"])

['46',
 '59',
 '104',
 '38',
 '54',
 '65',
 '109',
 '56',
 '104',
 '53',
 '41',
 '46',
 '87',
 '83',
 '39',
 '75',
 '46',
 '67',
 '101',
 '131',
 '54',
 '127',
 '64',
 '47',
 '35',
 '64',
 '96',
 '65',
 '67',
 '37',
 '44',
 '52',
 '71',
 '37',
 '86',
 '114',
 '39',
 '200',
 '81',
 '72',
 '109',
 '75',
 '58',
 '59',
 '59',
 '26',
 '43',
 '84',
 '103',
 '83',
 '59',
 '167',
 '65',
 '55',
 '96',
 '68',
 '68',
 '58',
 '78',
 '64',
 '52',
 '46',
 '69',
 '95',
 '70',
 '78',
 '114',
 '125',
 '116',
 '115',
 '115',
 '46',
 '135',
 '68',
 '104',
 '94',
 '32',
 '54',
 '59',
 '38',
 '115',
 '113',
 '75',
 '39',
 '58',
 '56',
 '109',
 '66',
 '46',
 '44',
 '80',
 '102',
 '41',
 '43',
 '244',
 '41',
 '245',
 '104',
 '122',
 '89',
 '61',
 '106',
 '68',
 '178',
 '42',
 '57',
 '41',
 '72',
 '96',
 '86',
 '59',
 '59',
 '64',
 '102',
 '72',
 '102',
 '41',
 '76',
 '51',
 '33',
 '58',
 '249',
 '109',
 '57',
 '119',
 '130',
 '140',
 '41',
 '73',
 '43',
 '120',
 '108',
 '141',
 '88',
 '89',
 '46',
 '90',
 '2

In [7]:
len(dataset.groupby("ID").count()['SignWidth'])

38485

In [8]:
dataset.groupby('DetectedCamera').count()

AngleOfSign     ID  SignAspectRatio  SignFacing  SignHeight  \
DetectedCamera                                                                
1                     10910  10910            10910       10910       10910   
2                      9298   9298             9298        9298        9298   
3                     10516  10516            10516       10516       10516   
4                      7761   7761             7761        7761        7761   

                SignWidth  
DetectedCamera             
1                   10910  
2                    9298  
3                   10516  
4                    7761

In [9]:
dataset.groupby('SignFacing').count()

AngleOfSign  DetectedCamera     ID  SignAspectRatio  SignHeight  \
SignFacing                                                                    
1                 21327           21327  21327            21327       21327   
2                   675             675    675              675         675   
3                   821             821    821              821         821   
4                 15662           15662  15662            15662       15662   

            SignWidth  
SignFacing             
1               21327  
2                 675  
3                 821  
4               15662

In [10]:
dataset[dataset['DetectedCamera'] == dataset['SignFacing']].shape

(19657, 7)

In [11]:
X = [[float(b) for b in list(w)] for w in dataset[['DetectedCamera','SignHeight','SignWidth','SignAspectRatio']].values]
y = [v for v in dataset['SignFacing'].values]
print(X[:10])
print(y[:10])

[[4.0, 45.0, 46.0, 1.02], [4.0, 54.0, 59.0, 1.09], [1.0, 108.0, 104.0, 0.96], [4.0, 47.0, 38.0, 0.81], [4.0, 58.0, 54.0, 0.93], [1.0, 78.0, 65.0, 0.83], [2.0, 117.0, 109.0, 0.93], [4.0, 54.0, 56.0, 1.04], [1.0, 109.0, 104.0, 0.95], [3.0, 103.0, 53.0, 0.51]]
[4, 4, 1, 4, 4, 1, 4, 4, 1, 1]


In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state = 0)

In [13]:
y_test[:10]

[1, 4, 4, 4, 1, 4, 1, 1, 4, 1]

In [14]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors = 3)
clf.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [15]:
clf.predict([4,'45','46','1.02'])

/home/aakash/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([4])

In [16]:
clf.score(X_test,y_test)

0.79089586364581166

In [17]:
clf.score(X_train,y_train)

0.87842566607767736

In [18]:
from sklearn.linear_model import LogisticRegression
lrclf = LogisticRegression(C = 0.001)
lrclf.fit(X_train,y_train)
print('Training accuracy :', lrclf.score(X_train,y_train))
print("Testing accuracy :", lrclf.score(X_test,y_test))

Training accuracy : 0.757578907251
Testing accuracy : 0.761276241946


In [19]:
lrclf.predict(X_test)

array([1, 4, 4, ..., 1, 4, 1])

In [20]:
lrclf.coef_


array([[ -1.01307701e+00,   2.16981089e-02,   7.70677932e-03,
         -3.57173459e-02],
       [ -2.09035248e-01,  -5.35708252e-02,   4.39668924e-03,
         -9.23085453e-04],
       [ -1.37997457e-02,  -5.80694611e-02,   9.72420388e-03,
         -8.42083689e-02],
       [  8.82375689e-01,  -1.74107269e-02,  -7.44223175e-03,
         -1.55962119e-01]])

In [21]:
from sklearn.svm import LinearSVC
lsvc = LinearSVC()
lsvc.fit(X_train,y_train)
#print('Training accuracy :', lsvc.score(X_train,y_train))
#print("Testing accuracy :", lsvc.score(X_test,y_test))

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [22]:
lsvc.coef_

array([[-0.5100903 ,  0.01461767, -0.00216655,  0.85259788],
       [-0.07769836, -0.00139295, -0.00470579,  0.14529045],
       [ 0.03021917,  0.00210234, -0.00635974,  0.14636655],
       [ 0.47376054, -0.01432036,  0.02747629, -1.34948366]])

In [23]:
print('Training accuracy :', lsvc.score(X_train,y_train))
print("Testing accuracy :", lsvc.score(X_test,y_test))

Training accuracy : 0.651041125316
Testing accuracy : 0.64591561006


In [24]:
from sklearn.naive_bayes import MultinomialNB,BernoulliNB,GaussianNB
mnbCl = MultinomialNB()
bnbCl = BernoulliNB()
gnbCl = GaussianNB()
mnbCl.fit(X_train,y_train)
bnbCl.fit(X_train,y_train)
gnbCl.fit(X_train,y_train)

GaussianNB(priors=None)

In [25]:
print('Training accuracy :', mnbCl.score(X_train,y_train))
print("Testing accuracy :", mnbCl.score(X_test,y_test))

Training accuracy : 0.751273256418
Testing accuracy : 0.75483267512


In [26]:
print('Training accuracy :', bnbCl.score(X_train,y_train))
print("Testing accuracy :", bnbCl.score(X_test,y_test))

Training accuracy : 0.554308283962
Testing accuracy : 0.553731033049


In [27]:
print('Training accuracy :', gnbCl.score(X_train,y_train))
print("Testing accuracy :", gnbCl.score(X_test,y_test))

Training accuracy : 0.741433669404
Testing accuracy : 0.74516732488


In [28]:
from sklearn.tree import DecisionTreeClassifier
treeCl = DecisionTreeClassifier(max_depth = 6,random_state=0)
treeCl.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=6,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=0, splitter='best')

In [29]:
print('Training accuracy :', treeCl.score(X_train,y_train))
print("Testing accuracy :", treeCl.score(X_test,y_test))

Training accuracy : 0.93455288778
Testing accuracy : 0.934317189773


In [30]:
treeCl.feature_importances_

array([ 0.93547321,  0.04765231,  0.00487035,  0.01200414])

In [76]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=500,random_state=0,max_features=3,max_depth=6)
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=6, max_features=3, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=500, n_jobs=1, oob_score=False, random_state=0,
            verbose=0, warm_start=False)

In [77]:
print('Training accuracy :', rfc.score(X_train,y_train))
print("Testing accuracy :", rfc.score(X_test,y_test))

Training accuracy : 0.934345009181
Testing accuracy : 0.935148617751


In [33]:
rfc.feature_importances_

array([ 0.85203939,  0.07643957,  0.04585853,  0.02566251])

In [53]:
from sklearn.ensemble import GradientBoostingClassifier
gbc = GradientBoostingClassifier(random_state=0,n_estimators=200,learning_rate=0.1,max_depth=7)
gbc.fit(X_train,y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=7,
              max_features=None, max_leaf_nodes=None,
              min_impurity_split=1e-07, min_samples_leaf=1,
              min_samples_split=2, min_weight_fraction_leaf=0.0,
              n_estimators=200, presort='auto', random_state=0,
              subsample=1.0, verbose=0, warm_start=False)

In [54]:
print('Training accuracy :', gbc.score(X_train,y_train))
print("Testing accuracy :", gbc.score(X_test,y_test))

Training accuracy : 0.963690538059
Testing accuracy : 0.922365412596


NameError: name 'np' is not defined